feat: added authentication in API and search api
fossology/LicenseDb pull request #12
Opened 2023-06-30 16:53 UTC by k-avy

feat: added authentication in API and search api
 * Get license with specific search term:
   * field: represents the name of field to be searched
   * search_term: represents the term to be searched
   *  search: represent the algorithm to search with
 * authenticate the API:
      * added the struct for user  
      *  created a user table in the database 
      *  added basic user endpoints:
         * get user using id 
         * get all user
         * create user
      * added basic authentication to all the API endpoints i.e, group of endpoints

2023-07-14 05:27 UTC, avinal commented
Please rebase

2023-07-19 08:07 UTC, avinal commented
It seems the rebase was not done correctly, please remove the first commit and rebase again.

2023-07-19 09:15 UTC, avinal requested changes
- Only use if you have to create a new string using some variables. Else directly put the string
- when you have a if statement such that the check is only used for the condiiton, combine assignment and if i.e
```go
if err := something.check(); err!= nil {
    // logic
}

// no further use of err
```
- write assignment and if separately if the check is to be reused or there are multiple assignments
```go
value, err := something.Check()
if err != nil {
    // logic
}

// or
val := something.Value()
// check 1
if val.x ... {
    // logic for val.x check
}

// check 2
if val.y ... {
   // logic for val.y check
|
```
keep these guidelines in mind

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +			Message:   fmt.Sprintf("invalid request"),
remove sprintf, helpful message

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Message:   fmt.Sprintf("Please check your credentials and try again"),
remove sprintf and this is a case of no credentails, indicate that.

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +			err := errors.New("authentication failed")
```suggestion
```
no need of creating error if you have to get the string again

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Error:     err.Error(),
write error like "error: no credentials were passed"

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Message:   fmt.Sprintf("Please check your credentials and try again"),
remove sprintf

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +		if result.Error != nil {
```suggestion
    err := api.DB.Where("username = ?", username).First(&user).Error
	if err != nil {
```

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Message:   fmt.Sprintf("User name not found"),
remove sprintf

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Error:     result.Error.Error(),
```suggestion
				Error:     err.Error(),
```

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Message:   fmt.Sprintf("Incorrect password"),
remove sprintf

2023-07-19 09:15 UTC, avinal commented on pkg/authenticate/auth.go
> +				Error:     result.Error.Error(),
```suggestion
				Error:     err.Error(),
```

2023-07-19 19:08 UTC, avinal requested changes
You have missed few changes, please fix them

2023-07-20 07:25 UTC, avinal approved these changes
looks good to me, cc @ag4ums

2023-07-20 13:46 UTC, GMishx requested changes

2023-07-20 13:46 UTC, GMishx commented on cmd/laas/main.go
> +	authorized.GET("/api/license/:shortname", api.GetLicense)
Why is getting a license requires authorization?

2023-07-20 13:46 UTC, GMishx commented on cmd/laas/main.go
> +	r.POST("/api/user", auth.CreateUser)
And creating a user does not require authentication?

2023-07-20 13:46 UTC, GMishx commented on cmd/laas/main.go
> +	authorized.GET("/api/licenses", api.SearchInLicense)
Same here, getting all licenses requires authentication?

2023-07-20 13:46 UTC, GMishx commented on cmd/laas/main.go
> +	authorized.PATCH("/api/license/update/:shortname", api.UpdateLicense)
Please use consistent plural form for the endpoints. It should be `/api/licenses/update/:shortname` or `/api/licenses/:shortname` not `/api/license/:shortname`.

You can work on it in a separate PR if needed.

2023-07-20 13:46 UTC, GMishx commented on pkg/api/api.go
> +	search_term := c.Query("search_term")
I would suggest to read the search term in the body. Keeping it in query limits the size of text someone can search.

Can we discuss it tomorrow @k-avy @avinal @ag4ums ?

2023-07-21 05:21 UTC, GMishx commented on cmd/laas/main.go
> +	authorized.GET("/api/license/:shortname", api.GetLicense)
Ummm... There the endpoint to list all users and specific user is unauthenticated.

Endpoints to Create/modify licenses and every endpoint related to users should be authenticated.

2023-07-28 08:38 UTC, avinal requested changes

2023-07-28 08:38 UTC, avinal commented on cmd/laas/main.go
> +	r.GET("/api/users/:id", auth.GetUser)
Add auth here

2023-08-01 15:48 UTC, avinal approved these changes
Looks great to me.

2023-08-02 12:01 UTC, ag4ums approved these changes
LGTM

2023-08-08 11:56 UTC, merged