feat: updated project structure and added basic test cases to project
fossology/LicenseDb pull request #13
Opened 2023-07-12 19:55 UTC by k-avy

### feat: updated the project structure and added test case

* updated project structure to avoid import cycle
  *  added a different package for database where:
     * there is function related to migration of database
     * and populating database

* added basic test cases:
  * added API test cases for create, update, get license by shortname and search in licenses
  * added user test cases for create and get user by id

* updated meta to pagination meta for better discription

2023-07-26 18:48 UTC, sjha2048 commented
There can be some more changes in the project structure, let's go over it in our next call.
I will update this comment after our discussion.

2023-08-21 09:27 UTC, avinal requested changes
Add the test command to the Github Actions as well.

2023-08-21 09:27 UTC, avinal commented on pkg/api/api.go
> +	r.GET("/api/licenses", FilterLicense)
Create an issue to merge these two endpoints into a single one.

2023-08-21 09:27 UTC, avinal commented on pkg/models/types.go
> +type PaginationMeta struct {
Create an issue to make this struct as free form key-value mapping field

2023-08-21 09:27 UTC, avinal commented on pkg/models/types.go
> +	Url             string `json:"rf_url" `
```suggestion
	Url             string `json:"rf_url"`
```

2023-12-04 05:47 UTC, merged