chores: Added README.d and basic CI.
fossology/LicenseDb pull request #4
Opened 2023-06-05 18:43 UTC by k-avy

Fixes issue: #3

2023-06-06 00:44 UTC, GMishx requested changes

2023-06-06 00:44 UTC, GMishx commented on .github/workflows/go.yml
> +# X-License-Identifier: GPL-2.0
```suggestion
# SPDX-License-Identifier: GPL-2.0-only
```
Please use the new license identifier. And update other files as well in a separate PR.

2023-06-06 00:44 UTC, GMishx commented on README.md
> +- Run the executable in your vscode terminal.
```suggestion
- Run the executable.
```

2023-06-06 13:14 UTC, avinal commented
Please squash the commits into one.

2023-06-06 13:15 UTC, avinal requested changes
Please squash the commits into one.

2023-06-06 13:19 UTC, avinal commented
@GMishx we need to enable GitHub Actions

2023-06-08 09:08 UTC, GMishx approved these changes

2023-06-08 09:08 UTC, merged