Make port in swagger docs configurable
fossology/LicenseDb pull request #46
Opened 2024-02-27 09:00 UTC by deo002

2024-02-27 09:24 UTC, avinal requested changes
Few suggestions

2024-02-27 09:24 UTC, avinal commented on pkg/api/api.go
> +	}
Seems fine, a better way would be to remove the else completely. And making this logic concise. 

```suggestion
  port := os.Getenv("PORT")
	if len(port) == 0 {
	  port = DEFAULT_PORT
	}
  docs.SwaggerInfo.Host = fmt.Sprintf("localhost:%s", port)
```

2024-02-27 09:24 UTC, avinal commented on pkg/api/api.go
> +const DEFAULT_PORT = 8080
```suggestion
const DEFAULT_PORT = "8080"
```

2024-02-28 08:43 UTC, avinal approved these changes
Please update the PR description and it should be good to be merged.

2024-02-28 11:42 UTC, GMishx approved these changes
Tested, working as expected.

2024-02-28 11:42 UTC, merged