add populating of database from JSON file
fossology/LicenseDb pull request #6
Opened 2023-06-08 07:31 UTC by k-avy

fixes #5 
 - added automigration capability
- added CLI arguments for database connection
- database can be populated with json file etc

2023-06-08 07:50 UTC, avinal commented
Will need to rebase once #4 is merged.

2023-06-08 09:15 UTC, GMishx requested changes

2023-06-08 09:15 UTC, GMishx commented on licenseRef.json
Please do not commit the json file to this repo. It will create duplication of data and requirement to update multiple files.

2023-06-08 09:15 UTC, GMishx commented on pkg/models/types.go
> +	TextYpdatable   string `json:"rf_text_updatable"`
```suggestion
	TextUpdatable   string `json:"rf_text_updatable"`
```

2023-06-08 09:15 UTC, GMishx commented on pkg/models/types.go
> +	SpdxCompatible  string `json:"rf_spdx_compatible"`
This field is updated to `rf_spdx_id`. Please update.

2023-06-08 12:25 UTC, avinal approved these changes
LGTM, tested

2023-06-12 10:26 UTC, avinal reviewed
As per discussion on Friday , we can go ahead with this code. Later, you will need to add duplicate protection and update the license from new JSON. Please create an issue for these task items.

2023-06-12 13:42 UTC, GMishx approved these changes

2023-06-12 13:42 UTC, merged