Feat: Docker Support for license DB
fossology/LicenseDb pull request #64
Opened 2024-05-31 10:19 UTC by Kaushl2208

1. Dockerfile --> Multi Build stage for LicenseDB application
2. docker-compose.yml --> Orchestrate Postgres and Application (LicenseDB)

To Test:

```
docker compose build
docker compose up -d 
```

Closes #63

2024-06-03 16:31 UTC, Kaushl2208 commented
@GMishx Can you review :)

2024-06-03 17:03 UTC, GMishx approved these changes
Changes looks good, needs test.

Thanks for the contribution.

2024-06-04 08:02 UTC, GMishx requested changes

2024-06-04 08:02 UTC, GMishx commented on docker-compose.yml
> +      - "5432:5432"
It is not a good idea to expose the database port by default. Please comment the lines.

2024-06-05 17:50 UTC, avinal approved these changes
Tested, working as expected.

Possible next steps: GitHub Actions for pushing images to GitHub/Docker registry on push/release.

2024-06-06 07:37 UTC, GMishx approved these changes
Changes looks good.

2024-06-06 07:50 UTC, merged