Category field added in obligation (get, post, patch)
fossology/LicenseDb pull request #84
Opened 2024-10-09 09:51 UTC by bhowmik94

## Changes

- 
- Fixes #issue_no

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [ ] Includes docs ( if changes are user facing)
- [ ] I have tested my changes locally.

## References

2024-10-15 12:33 UTC, GMishx commented
@bhowmik94 you need to commit the updated doc files after the `swag init` and `swag fmt`

2024-10-18 05:05 UTC, GMishx commented
@bhowmik94 make sure to update the PR description when you are creating one.

2024-10-18 05:10 UTC, GMishx commented
Tried adding `category` to an existing obligation and it failed.

```shell
curl -X 'PATCH' \
  'http://localhost:8085/api/v1/obligations/my%20obligation' \
  -H 'accept: application/json' \
  -H 'Authorization: my.token' \
  -H 'Content-Type: application/json' \
  -d '{
"category": "Distribute"
}'
```

The response is 200

```json
{
  "status": 200,
  "data": [
    {
      "id": 1,
      "topic": "",
      "type": "",
      "text": "",
      "classification": "",
      "modifications": false,
      "comment": "",
      "active": false,
      "text_updatable": false,
      "category": ""
    }
  ],
  "paginationmeta": {
    "resource_count": 1
  }
}
```

2024-10-21 09:39 UTC, bhowmik94 commented
@GMishx Kindly try the update request now.

2024-10-22 04:52 UTC, GMishx requested changes
Please check the `category` value against the allowed values from the `enums:"Distribution,Patent,Internal,Contractual,Export Control,General"`. Currently I can put any values in the field with a `PATCH` or a `POST` request.

Also, the export and import endpoints do not reflect this new field. Please fix it as well.

And please update the PR description!

2024-10-30 09:40 UTC, GMishx requested changes

2024-10-30 09:40 UTC, GMishx commented on cmd/laas/docs/docs.go
> +=======
Resolve the merge conflict.

2024-10-30 09:40 UTC, GMishx commented on cmd/laas/docs/docs.go
> +>>>>>>> 65d5aaf (fix: obligation POST, PATCH fixed for category)
Resolve the merge conflict.

2024-10-30 09:40 UTC, GMishx commented on cmd/laas/docs/docs.go
> +<<<<<<< HEAD
Resolve the merge conflict.

2024-10-30 09:40 UTC, GMishx commented on cmd/laas/docs/docs.go
> +>>>>>>> 65d5aaf (fix: obligation POST, PATCH fixed for category)
Resolve the merge conflict.

2025-01-22 09:27 UTC, closed without merging