feat: added user json as createdBy field in getLicense
fossology/LicenseDb pull request #89
Opened 2024-10-28 11:57 UTC by bhowmik94

## Changes

- Added user field as a json object for showing user information.
- Contains userid, username and userlevel.

- 
- Fixes #issue_no
#88 

## Submitter Checklist

- [ ] Includes tests (if there is a feature changed/added)
- [ ] Includes docs ( if changes are user facing)
- [ ] I have tested my changes locally.

## References

2025-01-16 09:18 UTC, deo002 commented on swagger-diff.txt
Remove this file

2025-01-16 09:19 UTC, deo002 commented
Load user on /licenses/{shortname} GET

2025-01-16 10:01 UTC, deo002 commented
Set createdBy field when a license is created while importing

2025-01-16 10:02 UTC, deo002 commented
Also, remove merge conflicts

2025-02-27 06:29 UTC, GMishx requested changes
Rest looks good. However, I can pass a user object while creating a license and spoof a userid.

2025-02-27 08:02 UTC, GMishx approved these changes
LGTM

2025-02-27 08:03 UTC, merged