feat: added GET endpoints
fossology/LicenseDb pull request #9
Opened 2023-06-14 16:25 UTC by k-avy

fixes the first two tasks of issue 1

This consists of two end points:
* Get all licenses
  * to get all the details of the licenses present in the database.
  * gets the data of all the data components present in the database.
 * Get licenses by shortname:
   *  to get the data of the license with the shortname passed as a parameter.
   * error when no such license found.

2023-06-15 06:48 UTC, avinal requested changes
Good work, few suggestions

2023-06-15 06:48 UTC, avinal commented on cmd/laas/main.go
> +	// password of the user
```suggestion
	// password of the database
```

2023-06-15 06:48 UTC, avinal commented on cmd/laas/main.go
> +	// boolean agument to whether update the database or not
```suggestion
	// auto-populate the database
```

2023-06-15 07:34 UTC, avinal commented on go.mod
>  go 1.18
```suggestion
go 1.20
```
go 1.18 has already reached EOL, please update your installation and then update this mod file.

2023-06-22 13:37 UTC, GMishx reviewed
Changes looks good. Please check the comments from @avinal

2023-06-29 13:20 UTC, ag4ums approved these changes
Changes looks good

2023-06-29 13:28 UTC, merged